### ISSUE TITLE
Improve setViewportSize logic

### ISSUE THREAD

**Issue by amitaibu** [webdriverio/webdrivercss#102]
Looking at the [MAX_TRIES](https://github.com/webdriverio/webdriverio/blob/master/lib/commands/setViewportSize.js#L53) logic, along with the [recent](https://github.com/webdriverio/webdriverio/pull/692) fix to handle the window size, we're seeing a new issue where the regression image isn't of the correct size.

![https___app_shoov_io___screenshots_6189](https://cloud.githubusercontent.com/assets/125707/9097347/c916d5fc-3bcb-11e5-8219-dc5e2b5afc9e.jpg)

I suspect we didn't see those issues before as simply the script would error our when we would get the negative value of the width, thus no regression was created.

Before trying to deal with a fix @christian-bromann , can you please explain know why need to execute the same command more than once?

Anyway, I believe we should better handle the fact that after 5 tries the window might still not be of the right size. We could repeat it as many times needed, and timeout / throw error after lets say 10 sec.

**Comment by christian-bromann** [comment]
> why need to execute the same command

what command?

This is IE right? Could it be related to a ratio issue we have in mobile as well? I wouldn't blame it on the windowHandleSize command. We need to find a way to normalise the document size according to the desktop ratio

**Comment by amitaibu** [comment]
> what command?

Sorry, I mean [this](https://github.com/webdriverio/webdriverio/blob/master/lib/commands/setViewportSize.js#L83-L85) part - re calling `setViewPort`.


> This is IE right?

No, chrome.

**Comment by christian-bromann** [comment]
> can you please explain know why need to execute the same command more than once?

To change the browser size we have `windowHandleSize` to do so. But it just changes the browser window size. In order to change it to our desired viewport size we need at least to repeat the process (of getting differences between document width and expected width and resize again) once. Since this can leads to element resizing as well it turned out to be a good idea to do that multiple times.

Example: let's say we want to have a viewport size of 500x500
1. call windowHandleSize(500,500)
2. the current viewportsize would be something 500 x 480 (url and status bar take the other 20px since we changed only the window size)
3. calculate difference (0, 20px)
4. increase window size to fit desired viewport size (500, 520px)
5. repeat at step 2

**Comment by amitaibu** [comment]
Ok, good explanation :) 

So why `MAX_TRIES = 5`? Shouldn't it be done after the 2nd try?
And if not, maybe 5 times isn't enough, (as I suspect it to be)?

**Comment by christian-bromann** [comment]
> Shouldn't it be done after the 2nd try?

As I mentioned: __Since this can leads to element resizing as well it turned out to be a good idea to do that multiple times.__
I've got a PR to limit it to 5 retries since it turned into an endless loop for a specific OS/browser combination.

> And if not, maybe 5 times isn't enough, (as I suspect it to be)?

Mhm..could be. Even though 5 times is a lot. If not we should think of a better approach to to get the browser resized.

**Comment by amitaibu** [comment]
I'm suspecting the negative value we get for the width could be a clue. Or even as a work around, maybe the count of 5 should be reset if the last value was negative.

I'm going to sleep over this ;)

**Comment by amitaibu** [comment]
I'm seeing this error often with the 640 size.

The result is different from requested width:

```
Result:
{ screenWidth: 400, screenHeight: 674 }
Size:
{ width: 640, height: 697 }
```

**Comment by amitaibu** [comment]
Closed in favor of https://github.com/webdriverio/webdriverio/issues/700
