### ISSUE TITLE
Is this still in development?

### ISSUE THREAD

**Issue by Xiphe** [webdriverio/webdrivercss#148]
This project seems a little unmaintained.

 - I cant get the example from readme to work
 - The [WebdriverIO `v3.0` uncompat note](https://github.com/webdriverio/webdrivercss/commit/20e1ee3aa0707ec7df49d3bbe324ad934644e8dc) has been placed in Jul 2015. - webdriverio is now on [4.0.5](https://github.com/webdriverio/webdriverio/releases/tag/v4.0.5)
 - The Latest commit on any of the public branches is 4 month old
 - though @christian-bromann sais this project will [be updated soon](https://github.com/webdriverio/webdrivercss/issues/145#issuecomment-209304645) 

I'm not sure if  should invest more time to get it to work or go with another solution. Could you provide some informations about the state of the project?

**Comment by christian-bromann** [comment]
Yes, I paused working on this because WebdriverIO was missing of some important mobile commands that are required to make visual regression testing smooth for mobile. All necessary changes have been made to WebdriverIO and I can now cycle back to WebdriverCSS again. However it will take one or two more month I think until I have something to release here.

**Comment by Xiphe** [comment]
Great, thanks for the quick update. I'll check back in a few moths than :)

**Comment by JigeshShah** [comment]
Hi Christian,

Is the above issue resolved
